package main

import (
	"context"
	"fmt"
	"log"

	"gvisor.dev/gvisor/pkg/buffer"
	"gvisor.dev/gvisor/pkg/tcpip"
	"gvisor.dev/gvisor/pkg/tcpip/header"
	"gvisor.dev/gvisor/pkg/tcpip/link/channel"
	"gvisor.dev/gvisor/pkg/tcpip/network/ipv4"
	"gvisor.dev/gvisor/pkg/tcpip/network/ipv6"
	"gvisor.dev/gvisor/pkg/tcpip/stack"
	"gvisor.dev/gvisor/pkg/tcpip/transport/icmp"
	"gvisor.dev/gvisor/pkg/tcpip/transport/tcp"
	"gvisor.dev/gvisor/pkg/tcpip/transport/udp"
)

const nicID = tcpip.NICID(1)
const tunnelMTU = 1400

// Stack is the userspace TCP/IP stack terminating the tunnel locally.
type Stack struct {
	s  *stack.Stack
	ep *channel.Endpoint
}

func NewStack(tun *Tunnel) (*Stack, error) {
	s := stack.New(stack.Options{
		NetworkProtocols: []stack.NetworkProtocolFactory{
			ipv4.NewProtocol, ipv6.NewProtocol,
		},
		TransportProtocols: []stack.TransportProtocolFactory{
			tcp.NewProtocol, udp.NewProtocol, icmp.NewProtocol4, icmp.NewProtocol6,
		},
	})
	ep := channel.New(512, tunnelMTU, "")
	if err := s.CreateNIC(nicID, ep); err != nil {
		return nil, fmt.Errorf("create NIC: %s", err)
	}
	ones, _ := tun.Mask.Size()
	addr := tcpip.AddrFrom4([4]byte{tun.ClientIP[0], tun.ClientIP[1], tun.ClientIP[2], tun.ClientIP[3]})
	pa := tcpip.ProtocolAddress{
		Protocol: ipv4.ProtocolNumber,
		AddressWithPrefix: tcpip.AddressWithPrefix{
			Address:   addr,
			PrefixLen: ones,
		},
	}
	if err := s.AddProtocolAddress(nicID, pa, stack.AddressProperties{}); err != nil {
		return nil, fmt.Errorf("add address: %s", err)
	}
	s.SetRouteTable([]tcpip.Route{
		{Destination: header.IPv4EmptySubnet, NIC: nicID},
		{Destination: header.IPv6EmptySubnet, NIC: nicID},
	})

	st := &Stack{s: s, ep: ep}
	go st.outboundPump(tun)
	return st, nil
}

// outboundPump forwards packets generated by the stack into the tunnel.
// Note: channel.Endpoint.Read is non-blocking; ReadContext blocks.
func (st *Stack) outboundPump(tun *Tunnel) {
	ctx := context.Background()
	for {
		pkt := st.ep.ReadContext(ctx)
		if pkt == nil {
			return
		}
		buf := pkt.ToBuffer() // caller-owned clone
		b := buf.Flatten()
		buf.Release()
		pkt.DecRef()
		if verbose {
			log.Printf("pump read %d bytes from stack", len(b))
		}
		if len(b) == 0 {
			continue
		}
		if err := tun.WritePacket(b); err != nil {
			log.Printf("tunnel write: %v", err)
			return
		}
	}
}

// Inject feeds a raw IP packet received from the tunnel into the stack.
func (st *Stack) Inject(pkt []byte) {
	var proto tcpip.NetworkProtocolNumber
	switch pkt[0] >> 4 {
	case 4:
		proto = ipv4.ProtocolNumber
	case 6:
		proto = ipv6.ProtocolNumber
	default:
		return
	}
	p := stack.NewPacketBuffer(stack.PacketBufferOptions{
		Payload: buffer.MakeWithData(pkt),
	})
	// Caller retains ownership across InjectInbound (see gVisor's tun device).
	st.ep.InjectInbound(proto, p)
	p.DecRef()
}

func (st *Stack) Close() {
	st.ep.Close()
	st.s.Close()
}
